name: ying
description: "萤 - 本地优先的倒数日应用。"
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: 19.5.0
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^4.1.1
  home_widget: 0.8.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
