name: ying
description: "萤 - 本地优先的倒数日应用。"
publish_to: "none"
version: 3.0.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  flutter_local_notifications: 19.5.0
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^4.1.1
  file_picker: ^10.3.10
  home_widget: 0.8.0
  http: ^1.6.0
  image: ^4.8.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  lunar: ^1.7.8
  path_provider: ^2.1.5
  pointycastle: 4.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/licenses/
